apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: prometheus-scaledobject
spec:
  minReplicaCount: 0
  maxReplicaCount: 2
  cooldownPeriod:  60
  pollingInterval: 30
  successfulJobsHistoryLimit: 5           
  failedJobsHistoryLimit: 5
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1  # Optional. Default: apps/v1
    kind: Rollout         # Optional. Default: Deployment
    name: platform                # Mandatory. Must be in the same namespace as the ScaledObject
    envSourceContainerName: saas-platform
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-k8s.monitoring.svc:9090
        metricName: http_requests_total
        threshold: '100'
        query: sum(rate(http_requests_total{deployment="my-deployment"}[2m]))
        authModes: "bearer"
      authenticationRef:
        name: keda-prom-creds