apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./base
- ./workflow-controller-rbac
- ./argo-server-rbac
- workflows/curator/curator-configmap-template.yaml
- workflows/curator/curator.yaml
- workflows/db-remover/db-remover.yaml
- workflows/init-platform/init-platform.yaml
- workflows/init-storefront/init-storefront.yaml
- workflows/rollouts/rollouts-promoting.yaml
- workflows/rollouts/rbac.yaml
- webhook-template.yaml
