apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: db-remover
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: db-remover
  triggers:
    - template:
        name: db-remover-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: db-remover-
              spec:
                entrypoint: db-remover-template
                arguments:
                  parameters:
                  - name: db_name
                    value: "hello world"
                workflowTemplateRef:
                  name: db-remover
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body.db_name
              dest: spec.arguments.parameters.0.value