apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      eventSourceName: resource
      eventName: app-delete
    - name: test-dep1
      eventSourceName: resource
      eventName: app-create
  triggers:
    - template:
        conditions: "test-dep1" # && - AND / || - OR "test-dep || test-dep1"
        name: creator-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: creator-
              spec:
                entrypoint: creator
                arguments:
                  parameters:
                  - name: resource
                    value: "JSON"
                workflowTemplateRef:
                  name: workflow-template-submittable
          parameters:
            - src:
                dependencyName: test-dep1
                dataKey: body
              dest: spec.arguments.parameters.0.value
    - template:
        conditions: "test-dep" # && - AND / || - OR "test-dep || test-dep1"
        name: remover-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: remover-
              spec:
                entrypoint: remover
                arguments:
                  parameters:
                  - name: resource
                    value: "JSON"
                workflowTemplateRef:
                  name: workflow-template-submittable
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body
              dest: spec.arguments.parameters.0.value