apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saas-c
  namespace: argocd
  labels:
    workflow: managed
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"  
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: tenant
  source:
    path: saas/overlays/saas-c
    repoURL: https://github.com/omnidark/sandbox
    targetRevision: HEAD
    kustomize:
      version: v3.5.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true