apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/manifest-generate-paths: . 
spec:
  destination:
    namespace: develop
    server: 'https://aks-f783f1e0.hcp.westus.azmk8s.io:443'
  project: tenant
  source:
    path: storage/persisten-volumes
    repoURL: https://github.com/omnidark/sandbox
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true