kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cms-content-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  volumeName: sandbox-cms-content
  storageClassName: ""