apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform
spec:
  replicas: 1
  template:
    metadata:
        annotations:
          vault.hashicorp.com/agent-configmap: "sandbox-platform-secret-configmap"
          vault.hashicorp.com/agent-requests-cpu: "25m"
          vault.hashicorp.com/agent-limits-cpu: "50m"   
    spec:
      initContainers:
        - name: init-sqldatabase
          env:
            - name: VC_SAMPLE_DATA_DB
              value: webstore-platform_source
        - name: init-platform
          imagePullPolicy: Always
          image: docker.pkg.github.com/virtocommerce/vc-deploy-containers/platform-installer:dev-test
          command:
            - "/bin/sh"
            - "-c"
          args:
            - "echo START INIT $(date +%Y-%m-%d-%H-%M-%S)
            && python3 install-modules.py \"$MODULES_CONFIG\" /mnt/Modules/*
            & python3 installer.py $(ELECTRONICS_THEME_URL) $(ELECTRONICS_THEME_LOCATION)
            & python3 installer.py $(B2B_THEME_URL) $(B2B_THEME_LOCATION)
            & python3 installer.py $(ASSETS_URL) $(ASSETS_LOCATION)"
      containers:
        - name: vc-platform-web
          # resources:
          #   requests:
          #     memory: "256Mi"
          #   limits:
          #     memory: "512Mi"
      nodeSelector:
        agentpool: applications
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

          