apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront
  labels:
    k8s-app: sandbox-storefront
spec:
  template:
    metadata:
      annotations:
        reloader.stakater.com/search: "true"
      labels:
        k8s-app: sandbox-storefront
    spec:
        containers:
        - name: vc-storefront-web
          resources:
            requests:
              cpu: 125m
              memory: "256Mi"
            limits:
              cpu: 125m
              memory: "512Mi"