apiVersion: v1
kind: PersistentVolume
metadata:
  name: sandbox-cms-content
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 200Mi
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: mc_aks-cluster-dev_aks-dev_westus#fusefdb1fe6c3d1c4b1d814#sandbox-cms-content
    fsType: ext4
    volumeAttributes:
      containername: sandbox-cms-content
      skuName: Premium_LRS
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: "blob-premium"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sandbox-cms-content-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  volumeName: sandbox-cms-content
  storageClassName: "blob-premium"