apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront
  labels:
    k8s-app: sandbox-storefront
spec:
  template:
    metadata:
      annotations:
        reloader.stakater.com/search: "true"
      labels:
        k8s-app: sandbox-storefront
    spec:
        initContainers:
        - name: init-storefront
          imagePullPolicy: Always
          image: docker.pkg.github.com/virtocommerce/vc-deploy-containers/platform-installer:dev-test
          command:
            - "/bin/sh"
            - "-c"
          args:
            - "python3 installer.py $(ELECTRONICS_THEME_URL) $(ELECTRONICS_THEME_LOCATION)
            && python3 installer.py $(B2B_THEME_URL) $(B2B_THEME_LOCATION)
            && python3 installer.py $(ASSETS_URL) $(ASSETS_LOCATION)"
          envFrom:
          - configMapRef:
              name: deployment-cm 
        volumeMounts:
          - mountPath: /mnt/cms-content
            name: cms-content-data
        containers:
        - name: vc-storefront-web
          resources:
            requests:
              cpu: 135m
              memory: "256Mi"
            limits:
              cpu: 135m
              memory: "512Mi"