apiVersion: batch/v1
kind: Job
metadata:
  name: app-sync
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: sync
        image: curlimages/curl
        command:
          - "curl"
          - "-d"
          - "{\"label\":\"saas-template\"}"
          - "-H"
          - "Content-Type: application/json"
          - "-X"
          - "POST"
          - "http://webhook-eventsource-svc.argo.svc.cluster.local:12000/saas-postsync"
      restartPolicy: Never
  backoffLimit: 2