kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dev
  name: rollouts-role
rules:
- apiGroups:
  - argoproj.io
  resources:
  - rollouts
  verbs:
  - 'pause'
  - 'promote'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rollouts-bind
  namespace: dev
subjects:
- kind: ServiceAccount
  name: sa-rollouts
  namespace: dev
roleRef:
  kind: Role
  name: rollouts-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-rollouts
  namespace: dev