apiVersion: batch/v1
kind: Job
metadata:
  name: app-sync
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: sa-rollouts
      restartPolicy: Never
      containers:
      - name: modules-installer
        image: docker.pkg.github.com/virtocommerce/vc-deploy-containers/platform-installer:v3
        env:
        - name: MODULES_CONFIG
          valueFrom:
            configMapKeyRef:
              name: modules-config
              key: modules.json
        command:
          - "/bin/sh"
          - "-c"
        args:
          - "echo START INIT $(date +%Y-%m-%d-%H-%M-%S)
          && python3 install-modules.py \"$MODULES_CONFIG\" /mnt/Modules/*"
        volumeMounts:
        - name: modules-volume
          mountPath: /mnt/Modules
          readOnly: false
      - name: argo-rollout
        image: kkisilevsky/argo-kubectl-rollouts:latest
        command:
          - "bin/bash"
          - "-c"
        args:
          - "kubectl argo rollouts pause saas-platform -n dev"
      volumes:
      - name: modules-volume
        persistentVolumeClaim:
          claimName: modules-volume
  backoffLimit: 2