apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- platform-deploy.yaml
- platform-cm.yaml
- platform-secrets.yaml

resources:
- ../../../common-base/saas-platform

images:
- name: docker.pkg.github.com/virtocommerce/vc-platform/platform
  newName: docker.pkg.github.com/virtocommerce/vc-platform/platform
  newTag: 3.49.0-master-182936ca