apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-secret-configmap
  annotations:
    reloader.stakater.com/match: "true" 
data:
    templates-base.hcl: |
        {{ with secret "secret/webstore-sso" }}
        export AzureAd__ApplicationId={{ .Data.ApplicationID }}
        {{ end }}
        {{ with secret "secret/webstore-sso" }}
        export AzureAd__TenantId={{ .Data.TenantID }}
        {{ end }}
        {{ with secret "secret/redis" }}
        export ConnectionStrings__RedisConnectionString=redis-cluster.redis:6379,password={{ .Data.REDIS_CLUSTER_PASS }},ssl=False,abortConnect=False
        {{ end }} 
        {{ with secret "secret/mssql" }}
        export ConnectionStrings__VirtoCommerce="Server=tcp:vc-dev-dbserver.database.windows.net,1433;Database=$(VC_PLATFORM_SERVICE)_$(VC_NAMESPACE);User ID=$(VC_INSTANCE)_$(VC_NAMESPACE)_user@vc-dev-dbserver;Password={{ .Data.db_saas_password }};Trusted_Connection=False;Encrypt=True;"
        {{ end }}

