apiVersion: apps/v1
kind: Deployment
metadata:
  name: debian
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: debian
  replicas: 1
  template:
    metadata:
      labels:
        app: debian
    spec:
      containers:
      - name: debian
        image: debian:buster
        command:
            - "/bin/sh"
            - "-c"
        args:
          - "sleep infinity"
        resources:
          requests:
            cpu: 500m
            memory: "2048Mi"
          limits:
            memory: "2048Mi"
            cpu: 500m
        ports:
        - containerPort: 80
      nodeSelector:
        agentpool: applications