apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: develop
namePrefix: loadtest-prod-
commonLabels:
  instance: loadtest-prod


patchesStrategicMerge:
- platform-deploy.yaml
- deployment-cm.yaml
- platform-cm.yaml
- ingress-https.yaml
- ingress.yaml

resources:
- ../../../common-base/platform-loadtest

images:
- name: docker.pkg.github.com/virtocommerce/vc-platform/platform
  newName: docker.pkg.github.com/virtocommerce/vc-platform/platform
  newTag: 3.40.0-alpha.11720-dev-6aead3c6
