apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sandbox
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .  
spec:
  destination:
    namespace: develop
    server: https://kubernetes.default.svc
  project: tenant
  source:
    path: sand-box-app/overlays/dev
    repoURL: https://github.com/omnidark/sandbox
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true